[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-ordinalize = "3.1.12"
num-bigint = "0.4.3"
rayon = "1.6.1"
regex = "1.7.1"